export const managementErrorCodes = [
  "MANDATE_NOT_FOUND",
  "PROFILE_NOT_FOUND",
  "INVALID_STATE_TRANSITION",
  "SCHEMA_VALIDATION_FAILED",
  "CEILING_VIOLATION",
  "CONSISTENCY_CHECK_FAILED",
  "INSUFFICIENT_AUTHORITY",
  "MANDATE_NOT_DRAFT",
  "MANDATE_NOT_ACTIVE",
  "MANDATE_NOT_SUSPENDED",
  "MANDATE_EXPIRED",
  "BUDGET_DECREASE_NOT_ALLOWED",
  "TTL_DECREASE_NOT_ALLOWED",
  "DELEGATION_DEPTH_EXCEEDED",
  "DELEGATION_SCOPE_WIDENING",
  "DELEGATION_BUDGET_EXCEEDED",
  "DELEGATION_TTL_EXCEEDED",
  "PARENT_MANDATE_NOT_ACTIVE",
  "DUPLICATE_MANDATE",
  "DUPLICATE_CONSUMPTION_REPORT",
  "RATE_LIMITED",
  "INTERNAL_ERROR",
] as const;

export type ManagementErrorCode = (typeof managementErrorCodes)[number];

export const ERROR_CODE_HTTP_STATUS: Record<ManagementErrorCode, number> = {
  MANDATE_NOT_FOUND: 404,
  PROFILE_NOT_FOUND: 404,
  INVALID_STATE_TRANSITION: 409,
  SCHEMA_VALIDATION_FAILED: 422,
  CEILING_VIOLATION: 422,
  CONSISTENCY_CHECK_FAILED: 422,
  INSUFFICIENT_AUTHORITY: 403,
  MANDATE_NOT_DRAFT: 409,
  MANDATE_NOT_ACTIVE: 409,
  MANDATE_NOT_SUSPENDED: 409,
  MANDATE_EXPIRED: 409,
  BUDGET_DECREASE_NOT_ALLOWED: 422,
  TTL_DECREASE_NOT_ALLOWED: 422,
  DELEGATION_DEPTH_EXCEEDED: 422,
  DELEGATION_SCOPE_WIDENING: 422,
  DELEGATION_BUDGET_EXCEEDED: 422,
  DELEGATION_TTL_EXCEEDED: 422,
  PARENT_MANDATE_NOT_ACTIVE: 409,
  DUPLICATE_MANDATE: 409,
  DUPLICATE_CONSUMPTION_REPORT: 409,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
};

export class ManagementError extends Error {
  readonly code: ManagementErrorCode;
  readonly httpStatus: number;

  constructor(code: ManagementErrorCode, message: string) {
    super(message);
    this.name = "ManagementError";
    this.code = code;
    this.httpStatus = ERROR_CODE_HTTP_STATUS[code];
  }
}
